### ISSUE TITLE
PC2 - Issue Tracking

### ISSUE THREAD

**Issue by ammalagonc** [foundryvtt/pf2e#15804]
Alchemist 
- [x] Retool Feats to use Field Discoveries (#16019).
-  Sticky Bomb  (#16029)

Barbarian
- [x] Mighty Rage Automation (#15777)

Champion
- [x] Greater Security feat (#15765)
- [ ] Blessed Counterstrike
- [x] Effects with duration for Expand Aura (#15765)

Sorcerer
- [x] Additional blood magic effects (#15814)

Please add any issues encountered here.

**Comment by TikaelSol** [comment]
- [ ] Blessed Counterstrike automation #15761 
- [ ] Add Expand Aura effect #15760
- [ ] Automate Scaly Hide feat #15726 (Use the same automation used in scales of the dragon or animal skin)
- [ ] Oracle Cursebound condition does not work properly #15682

**Comment by TikaelSol** [comment]
Blessed Counterstrike is unautomatable.
