### ISSUE TITLE
Action Macro Improvements

### ISSUE THREAD

**Issue by TikaelSol** [foundryvtt/pf2e#15855]
- [ ] Action macros should gather parent roll options when embedded in an item #15754
- [ ] Unarmed athletics skill actions should benefit from agile trait #15120
- [ ] Recall Knowledge macro does not gather target roll options #15214
- [ ] Add a Take Cover macro #14731 (check off if no interest)
- [ ] Redo the Treat Wounds macro #6290
- [ ] The Escape action lacks roll options #14224

**Comment by ammalagonc** [comment]
- [ ]  Convert Action Macros to new Action Implementation
- Affects Risky Surgery (https://github.com/foundryvtt/pf2e/issues/16086)

**Comment by sangdrax8** [comment]
It seems that when selecting a higher DC in the first popup of the treat wounds macro (so from 15 to 20), that the following roll doesn't actually adjust the DC nor does it provide the static bonus healing for the higher DC.
