### ISSUE TITLE
Familiar Improvements

### ISSUE THREAD

**Issue by TikaelSol** [foundryvtt/pf2e#15858]
- [ ] Add support for languages #1141
- [ ] Add support for specific familiars #3551
- - [ ] Elemental Wisp Resonance #10153
- - [ ] Talking Head Skilled #11660
- [ ] Add shared vision for familiars (and potentially other companions) #3797
- [ ] Add support for SpecialStatistic RE on familiars #15584
