### ISSUE TITLE
The Big Bulk Tracking Ticket

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/pf2e#354]
In GitLab by @putt1 on May 13, 2020, 16:18

Things that are not yet implemented

* [x] GUI and data model to store bulk reduction (Bag of Holding, Backpack)
* [x] GUI and data model to store maximum container bulk values (very tricky: Gloves of storing hold a single item of 1 bulk or less, Belt Pouch holds 4L item,s Bandolier holds 8L items or a single set of tools, bag of holdings can store up to 150 bulk)
* [x] Coins should be stored in the inventory so that you can move them into various containers to reduce bulk, the current location should be readonly and show the full amount
* Container system
  * [x] A way to put items into a container
  * [x] Nesting a container into a container (e.g. Bag of Holding into a Backpack)
* [x] Coins having bulk is a config option -- on by default -- for GMs to disable if they wish

Ideas and mockups welcome
