### ISSUE TITLE
Tracking Issue: Spell system improvements

### ISSUE THREAD

**Issue by TikaelSol** [foundryvtt/pf2e#4882]
Condensing older issues into one place. Not all will be implemented, just trying to cut down on issues to a manageable number.

- [ ] Stave spellcasting #413
- [ ] Critical Rolls on spells, for spells with different critical scaling like Phantasmal Killer #547
- [ ] Create drag and drop interchangeable spell preparation lists #110
- [ ] Allow spell lists to be sorted alphabetically #485
- [ ] Some spells have 3D or other odd areas #1386
- [ ] Create spellcasting entries with features / feats
- [ ] Grant spell items from other items #2008
- [ ] Allow for spells with multiple spell types #1905
- [ ] Allow for alternate target DCs (Shadow Signet)
- [ ] Add heightened info to chat message data #2122 (May be already done)
- [ ] Fix healing spells getting damage bonuses #2071
- [ ] Allow spellcasting entries to be collapsed #2202
- [ ] Allow individual spell levels to be collapsed #2304
- [ ] Spell variants are orphaned when cast from a consumable #3382

**Comment by ThingsCouldGetDicey** [comment]
may i suggest to have spells that are of different origin i.e from an archetype or different magic orgiin i.e occultism etc etc. to be tabbed as a miniture tab. rather than one long list?

**Comment by MrVauxs** [comment]
you can already do that by making multiple spell lists, and for archetypes and different magic origins you frankly should

**Comment by ThingsCouldGetDicey** [comment]
> you can already do that by making multiple spell lists, and for archetypes and different magic origins you frankly should

what i meant was to have it tabbed as so 
![image](https://user-images.githubusercontent.com/62528192/203167758-dab3e3cd-2bde-4b86-9fd2-cb1935ba8776.png)
or something close to that. 
so you can click from different sources.

**Comment by ThingsCouldGetDicey** [comment]
![image](https://user-images.githubusercontent.com/62528192/203187758-2c56ae10-b006-483d-93a9-5c7f62360b77.png)
 a better mock up.

**Comment by TikaelSol** [comment]
On potential way to handle organization by tab is by allowing custom tabs. It's not feasible to add a tab for each source as that becomes a bigger mess fairly quickly due to the number of sources.

![image](https://user-images.githubusercontent.com/80183198/203377163-eb8d1b2b-3be9-47ed-85c3-389cd6e7dd5e.png)

However we do a spell sheet redesign it will be fairly contentious I think. There's a lot of data to track there and people are going to be opinionated about how to tackle it. It's possible that we build out the spell sheet with multiple UIs in mind so modules can more easily be made / maintained to provide the UI people want.

**Comment by TikaelSol** [comment]
For handling amped spells or Spell Trickster we want a way to inject a variant spell, including the ability to cast regular spells with focus points.  Something like

```
{
    "key": "SpellVariant",
    "override": {
        "damageDice": "d12",
        "range": "touch",
        "heightening": {
            "damage": {
                "fire": "d12",
                "interval": 1
            }
        }
    },
    "label": "Amped Melee",
    "focus": true
}
```
We can almost do this now, if we use a DamageDice override on produce flame to d10 predicated on `target:distance:5` it would automate the melee range improvement on adjacent enemies, but the condition is melee which means we'd needs to account for reach improvements, even ones as silly as tentacular limbs which could grant a temporary range for the spell of 60+ feet. So to handle that a variant is likely the best otherwise people are dragging new effects to themselves all the time.

**Comment by ThingsCouldGetDicey** [comment]
i do think damage type would be useful as a quick reference regardless of what happens.

**Comment by ammalagonc** [comment]
- [ ]  Shield of the Spirit (#16007)

**Comment by pedrogrullada** [comment]
- [ ] Add support for area size increase when heightening on an interval.

**Comment by maplealmond** [comment]
Adding to this tracking issue, the various special wands (e.g. Wand of Shattering Images) are *equipment* and not *consumables* and they do not have their respective spells appear in the activations tab.

I'm not sure if this should be solved by having equipment more generally grant activations, or migrating the specialty wands over to consumables. (I would love to see the former for various reasons but appreciate this might be difficult.)

**Comment by pedrogrullada** [comment]
- [ ] Support spells with multiple damage formulas, such as for different degrees of success, like _phantasmal killer_ and _hydraulic push_
- [ ] Allow DCs from different spellcasting entries to be referenced in inline DCs, or alternatively allow for multiple types of saves in a single spell.

**Comment by simonward** [comment]
- [ ] Structured support for common spell qualifiers ie. At Will, Constant, Self Only
